plugins {
    id "net.fabricmc.fabric-loom" version "1.17.16" apply false
    id "net.neoforged.moddev" version "2.0.141" apply false
}

def getAppVersion = { ->
    try {
        def result = providers.exec {
            commandLine 'git', 'tag', '--points-at', 'HEAD'
            ignoreExitValue = true
        }
        def tag = result.standardOutput.asText.get().trim()
        if (tag.isEmpty()) {
            return minecraft_version + "-SNAPSHOT"
        }
        return tag
    } catch (Exception e) {
        println "Warning: ${e.message}, is git installed?"
        return minecraft_version + "-DEV"
    }
} as Object

allprojects {
    version = getAppVersion()
}
