org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neo_form_version=26.2-1
java_version=25

archives_base_name=immersive_armors
mod_name=Immersive Armors
mod_author=Luke100000
mod_id=immersive_armors
license=GPL-3.0-only

fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.2

cloth_version=26.2.155
mod_menu_version=20.0.1

neoforge_version=26.2.0.25-beta
neoforge_loader_version_range=[4,)
