org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
yarn_mappings_patch_neoforge_version = 1.21+build.4

archives_base_name=immersive_armors

fabric_loader_version=0.16.14
fabric_api_version=0.115.6+1.21.1

cloth_version=15.0.130
mod_menu_version=11.0.2

neoforge_version=21.1.169