plugins {
    id "multiloader-loader"
    id "net.neoforged.moddev"
}

neoForge {
    version = neoforge_version
    runs {
        configureEach {
            ideName = "NeoForge ${name.capitalize()} (${project.path})"
        }
        client {
            client()
            gameDirectory = file("runs/client")
        }
        server {
            server()
            gameDirectory = file("runs/server")
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

def loaderAttribute = Attribute.of("io.github.mcgradleconventions.loader", String)
["apiElements", "runtimeElements", "sourcesElements"].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, "neoforge")
        }
    }
}

sourceSets.configureEach {
    [compileClasspathConfigurationName, runtimeClasspathConfigurationName, getTaskName(null, "jarJar")].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, "neoforge")
            }
        }
    }
}
