name: Java CI with Gradle

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle - Forge
        run: ./gradlew :forge:build
      - name: Build with Gradle - Fabric
        run: ./gradlew :fabric:build
      - name: Upload Artifacts - Forge
        uses: actions/upload-artifact@v7
        with:
          name: forge_artifacts
          path: ./forge/build/libs/
      - name: Upload Artifacts - Fabric
        uses: actions/upload-artifact@v7
        with:
          name: fabric_artifacts
          path: ./fabric/build/libs/
      - name: Upload Fabric to CurseForge
        uses: Kira-NT/mc-publish@v3.3.1
        with:
          curseforge-id: 580681
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

          name: "[Fabric 1.17.1] Immersive Armors - ${{ github.ref_name }}"
          version: ${{ github.ref_name }}
          changelog-file: changelog.md
          version-type: release
          files: "fabric/build/libs/immersive_armors-${{ github.ref_name }}.jar"
          loaders: |
            fabric
          environment: client | server
          game-versions: |
            1.17.1
          java: |
            Java 16

          fail-mode: skip
      - name: Upload Forge to CurseForge
        uses: Kira-NT/mc-publish@v3.3.1
        with:
          curseforge-id: 580681
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

          name: "[Forge 1.17.1] Immersive Armors - ${{ github.ref_name }}"
          version: ${{ github.ref_name }}
          changelog-file: changelog.md
          version-type: release
          files: "forge/build/libs/immersive_armors-${{ github.ref_name }}.jar"
          loaders: |
            forge
          environment: client | server
          game-versions: |
            1.17.1
          java: |
            Java 16

          fail-mode: skip
